# https://docs.gitlab.com/ce/ci/yaml/README.html

###### GENERAL ################################################################
image: node:8.11.2

###### TEMPLATES ##############################################################
.general: &general
  tags:
    - gitlab-org
  variables:
    GIT_STRATEGY: fetch

###### STAGES #################################################################
stages:
  - install
  - test
  - build
  - deploy

###### JOBS ###################################################################
install:
  <<: *general
  stage: install
  cache:
    policy: pull-push
    paths:
      - node_modules
  script:
    - yarn install
  only:
    - master

test:
  <<: *general
  stage: test
  cache:
    policy: pull
  dependencies: []
  artifacts:
    paths:
      - coverage
    expire_in: 1 month
  script:
    - yarn test --ci --coverage
  only:
    - master

build:
  <<: *general
  stage: build
  cache:
    policy: pull
  dependencies: []
  script:
    - yarn build
  artifacts:
    expire_in: 1 day
    paths:
      - build
  only:
    - master

deploy:
  <<: *general
  image: sergeyfast/alpine-rsync
  stage: deploy
  cache: {}
  dependencies:
    - build
  before_script:
    - eval $(ssh-agent -s)
    - mkdir -m 700 -p ~/.ssh
    - echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-add ~/.ssh/id_rsa
  script:
    - rsync -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet' build/* ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_PATH} --delete-after -r -v
  only:
    - master
