# https://docs.gitlab.com/ce/ci/yaml/README.html

###### GENERAL ################################################################
image: node:8.11.2

###### TEMPLATES ##############################################################
.general: &general
  tags:
    - gitlab-org
  variables:
    GIT_STRATEGY: fetch

###### STAGES #################################################################
stages:
  - install
  - test
  - build
  - deploy

###### JOBS ###################################################################
install:
  <<: *general
  stage: install
  script:
    - yarn install
  artifacts:
    expire_in: 1 day
    paths:
      - node_modules
  only:
    - master

test:
  <<: *general
  stage: test
  artifacts:
    paths:
      - coverage
    expire_in: 1 month
  script:
    - yarn test --ci --coverage
  only:
    - master

build:
  <<: *general
  stage: build
  dependencies:
    - install
  script:
    - yarn build
  artifacts:
    expire_in: 1 day
    paths:
      - build
  only:
    - master

deploy:
  <<: *general
  stage: deploy
  dependencies:
    - build
  script:
    - ${update_pages}
  only:
    - master
